- name: Check syntax of PHP-CLI php.ini configuration
  shell: >
    php -e --version --php-ini '{{ php_path_cli }}/php.ini'
  register: result
  failed_when: result.rc != 0 or result.stderr != ''
  changed_when: result.rc != 0 or result.stderr != ''


- name: Check syntax of PHP-FPM configuration
  shell: >
    php5-fpm -e --test --php-ini '{{ php_path_fpm }}/php.ini'
  register: result
  failed_when: result.rc != 0
  changed_when: result.rc != 0


- name: Ensure PHP-FPM service is started
  service: name=php5-fpm state=started enabled=yes
  tags: [php, packages, config]
